grafana:
  default: {}
  global:
    projects:
      console:
        envs:
          hprod:
            groups:
            - /admin
            - /admin
            tenants:
              hprod-dso: {}
          prod:
            groups:
            - /admin
            - /admin
            tenants:
              prod-dso: {}
        projectName: dso
        projectRepository:
          path: roles/gitops/rendering-apps-files/templates/dashboard
          url: https://github.com/cloud-pi-native/socle.git
  grafana:
    adminPassword: docker.io
    isOpenShift: true
    observatorium_url: http://sandbox-dso-observatorium-api.dso-observatorium.svc.cluster.local:8080
  grafana-operator:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: operator
                app.kubernetes.io/instance: sandbox-dso-grafana
                app.kubernetes.io/name: grafana-operator
            topologyKey: kubernetes.io/hostname
          weight: 100
    isOpenShift: true
  grafanaNamespace: dso-grafana
  oauth:
    aud: grafana
    enabled: true
    groups_attribute_path: group
    id: docker.io
    scopes: profile, email, openid, group
    secret: docker.io
    url: https://docker.io/realms/dso
  server:
    certManager:
      enabled: true
    ingressClassName: traefik
    url: docker.io
observatorium:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: api
              app.kubernetes.io/instance: sandbox-dso-observatorium
              app.kubernetes.io/name: observatorium
          topologyKey: kubernetes.io/hostname
        weight: 100
  api:
    config:
      clientID: account
      groupClaim: groups
      groups:
      - /admin
      id: prod-infra
      issuerURL: https://docker.io/realms/dso
      name: prod-infra
      usernameClaim: preferred_username
    loglevel: info
  global:
    projects:
      console:
        envs:
          hprod:
            groups:
            - /admin
            - /admin
            tenants:
              hprod-dso: {}
          prod:
            groups:
            - /admin
            - /admin
            tenants:
              prod-dso: {}
        projectName: dso
        projectRepository:
          path: roles/gitops/rendering-apps-files/templates/dashboard
          url: https://github.com/cloud-pi-native/socle.git
  ingress:
    enabled: false
  logs:
    enabled: false
    read:
      endpoint: docker.io
    rules:
      endpoint: docker.io
    tail:
      endpoint: docker.io
    write:
      endpoint: docker.io
  metrics:
    alertmanager:
      endpoint: docker.io
    enabled: false
    read:
      endpoint: docker.io
    rules:
      endpoint: docker.io
    tenantHeader: X-Scope-OrgId
    write:
      endpoint: docker.io
