apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: dso-argocd
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`docker.io`)
    services:
    - name: conf-dso-argocd-server
      port: 80
  tls:
    secretName: argo-ingress-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-appset-ingress
  namespace: dso-argocd
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`appset.docker.io`)
    services:
    - name: conf-dso-argocd-applicationset-controller
      port: 7000
  tls:
    secretName: argo-appset-ingress-tls
