---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: dso-argocd
  annotations:
    route.openshift.io/termination: edge
  labels:
spec:
  ingressClassName: docker.io
  rules:
    - host: docker.io