---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-proxy
  namespace: dso-nexus
  annotations:
    route.openshift.io/termination: edge
  labels:
    app: nexus
spec:
  ingressClassName: docker.io
  rules:
    - host: docker.io