---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: dso-vault
  annotations:
    route.openshift.io/termination: edge
  labels:
    app: vault
spec:
  ingressClassName: docker.io
  rules:
    - host: vault.infra.polyops.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conf-dso-vault-active
                port:
                  number: 8200
