apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingress
  namespace: dso-vault
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vault.infra.polyops.fr`)
    services:
    - name: conf-dso-vault-active
      port: 8200
  tls:
    secretName: vault-ingress-tls
